### ISSUE TITLE
Error using GraphStreamViewer

### ISSUE THREAD

**Issue by ambasta** [jsprit/jsprit#197] opened 2015-12-02 08:41 UTC
Hi,

While using GraphStreamViewer as
```
new GraphStreamViewer(
    odxRoutingProblem).labelWith(
    Label.ID).setRenderShipments(
    true).setRenderDelay(150).display();
```

I get a 

```
Exception in thread "main" org.graphstream.graph.IdAlreadyInUseException: singleton exception: id "243451218_[x=12.953537][y=77.697951]" already in use. Cannot create a node.
	at org.graphstream.graph.implementations.AbstractGraph.addNode(AbstractGraph.java:321)
	at jsprit.analysis.toolbox.GraphStreamViewer.renderShipment(GraphStreamViewer.java:518)
	at jsprit.analysis.toolbox.GraphStreamViewer.render(GraphStreamViewer.java:397)
	at jsprit.analysis.toolbox.GraphStreamViewer.display(GraphStreamViewer.java:334)
	at vrppdtw.base.OdxVehicle.main(OdxVehicle.java:366)
```

Any ideas why?

**Comment by oblonski** [comment] 2015-12-02 14:38
Can you make your problem small so that you still have this error and send it to me? Otherwise it will be hard to reproduce.

**Comment by oblonski** [comment] 2016-01-05 19:24
Since there is no answer to my response, I assume this issue is actually no issue anymore? Can I close this?

**Comment by ambasta** [comment] 2016-01-05 20:05
Sorry, yes please do!

On Wed, Jan 6, 2016 at 12:54 AM, Stefan Schröder <notifications@github.com>
wrote:

> Since there is no answer to my response, I assume this issue is actually
> no issue anymore? Can I close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsprit/jsprit/issues/197#issuecomment-169103618>.
>



--

**Closed** 2016-01-05 20:06 UTC
Labels: bug
