### ISSUE TITLE
Question on business case

### ISSUE THREAD

**Issue by demonicmetalcs** [jsprit/jsprit#160] opened 2015-05-19 12:24 UTC
Good afternoon,
 
We have a business case which we are trying to adapt JSprit for and so far we're very impressed with the results. We have a scenario though which seems very inefficient and I was wondering if you have a solution or a different way of handling this.
 
The goal is to schedule jobs for a longer period of time. For example we have 60 mechanics and 2500 orders they have to get through in a month. What we do right now is do the calculations for 1 day, take away the scheduled orders from the batch and do another calculation for the next day etc. etc. till we have scheduled a full month.
 
The issue here being that we basically do 2000 iterations for every day in the selection. This also means that we would never be able to schedule out a full year for example, because of the time it takes with big selections. (30000 jobs for 4 mechanics already took us 40ish seconds per iteration). 
 
To put it a bit more concrete, we would like the ability to schedule in routes over a longer period of time taking into account obviously that a mechanic does not work 24 hours a day. Our current approach is as mentioned, we calculate a new route for every day removing the ones we already scheduled. Is this the right approach? 
 
Thank you very much for your help, I am looking forward to your input. 
 
Kind regards, 
 
Connor.

**Comment by PGWelch** [comment] 2015-05-19 12:48
Could you just create multiple 'vehicles' corresponding to multiple days for the same mechanic? i.e. have a vehicle 'connor day 1', another 'connor day 2' etc?
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com
		 ---- On Tue, 19 May 2015 13:24:38 +0100  notifications@github.com  wrote ----Good afternoon,
We have a business case which we are trying to adapt JSprit for and so far we're very impressed with the results. We have a scenario though which seems very inefficient and I was wondering if you have a solution or a different way of handling this.
The goal is to schedule jobs for a longer period of time. For example we have 60 mechanics and 2500 orders they have to get through in a month. What we do right now is do the calculations for 1 day, take away the scheduled orders from the batch and do another calculation for the next day etc. etc. till we have scheduled a full month.
The issue here being that we basically do 2000 iterations for every day in the selection. This also means that we would never be able to schedule out a full year for example, because of the time it takes with big selections. (30000 jobs for 4 mechanics already took us 40ish seconds per iteration). 
To put it a bit more concrete, we would like the ability to schedule in routes over a longer period of time taking into account obviously that a mechanic does not work 24 hours a day. Our current approach is as mentioned, we calculate a new route for every day removing the ones we already scheduled. Is this the right approach? 
Thank you very much for your help, I am looking forward to your input. 
Kind regards, 
Connor.

**Comment by demonicmetalcs** [comment] 2015-05-19 12:51
that is a good solution to the vehichles timewindows but would you do the same for the orders time window because that would make the orders multiply by 30 and i think this would slow down the calculation

**Comment by oblonski** [comment] 2015-05-19 13:07
Hi,

If you have order time-windows then Phil's suggestion is not feasible.
but I also thought that you do not have any restriction apart from the
working time of a driver. just to understand your problem better, on the
one hand you have order time windows that are related to a day, e.g.
this order needs to be done between 9am and 10am. On the other hand the
day the order is served is not relevant? the order can be served in the
course of a year? gives us little more information about your problem.

Best stefan

Am 19/05/15 um 14:51 schrieb demonicmetalcs:

**Comment by demonicmetalcs** [comment] 2015-05-19 13:43
Hello Stefan,

Thank you for taking an interest in our ticket. To answer your question, we want to use it for service level agreements. This means the date is also important for us. 

Regards,

Connor

**Comment by oblonski** [comment] 2015-05-19 13:46
I understand, but the question remains whether you schedule your drivers
first and make the service level aggreement afterwards or the other way
around?

Am 19/05/15 um 15:43 schrieb demonicmetalcs:

**Comment by PGWelch** [comment] 2015-05-19 13:50
Do you have several dates that a mechanic could service a job? If so, do these have the same time window (i.e. always 9am to 11am, regardless of the date) or different time windows?

**Comment by demonicmetalcs** [comment] 2015-05-19 13:50
Hello Stefan,

We have mechanics who just work from 9 to 5 and the service level agreements are set on the orders we receive. So the mechanics already have their schedule and the service level agreements are already in place on the order. The mechanics will also do regular maintainance etc. which do not have any service level agreements on it. Hope that makes it more clear.

Regards,

Connor

**Comment by demonicmetalcs** [comment] 2015-05-19 13:51
To command on PGWelch

It could differ per day


Do you have several dates that a mechanic could service a job? If so, do these have the same time window (i.e. always 9am to 11am, regardless of the date) or different time windows?

**Comment by oblonski** [comment] 2015-05-19 14:05
But then - I guess - Phil's suggestion could work. Plan a week from
Monday to Friday (in Minutes) like this:

driver:
connor_monday, start: 9*60, end: 17*60
connor_tuesday, start: 24*60+9*60, end: 24*60+17*60
....

orders:
orders without any time-window, e.g. regular maintenance
order1
order2
...

orders with time-window
monday: order_tw_1, earliest: 10*60, latest: 11*60
monday: order_tw_2, earliest: 13*60, latest:14*60
tuesday: order_tw_3, earliest: 24*60+10*60, latest: 24*60+13*60
...




Am 19/05/15 um 15:50 schrieb demonicmetalcs:

**Comment by oblonski** [comment] 2015-05-19 14:11
If you want connor to serve roughly the same area every day, you should
somehow enforce that connor needs to serve certain order, e.g. by
assigning a skill 'connor's place' to connor and to at least one order
in connor's area.

Am 19/05/15 um 16:05 schrieb Stefan Schroeder:

**Comment by demonicmetalcs** [comment] 2015-05-19 14:16
Isn't this going to slow the calculation down by adding in to much orders?
And if the order with time window gets planned in on monday and tuesday than it is planned in twice

**Comment by oblonski** [comment] 2015-05-19 14:27
If you are able to reasonably divide your big problem into smaller ones,
it is always better in terms of computation time.

> And if the order with time window gets planned in on monday and
> tuesday than it is planned in twice
>

No. I assumed that these are unique orders since I understood from your
description that for some orders you already have a time schedule, i.e.
day of order (e.g. Monday) and time window (11-12).

**Comment by demonicmetalcs** [comment] 2015-05-19 14:28
But say it would be the same order?

**Comment by oblonski** [comment] 2015-05-19 14:30
That would not make much sense, since then you try to assign it several
times.

Am 19/05/15 um 16:28 schrieb demonicmetalcs:

**Comment by PGWelch** [comment] 2015-05-19 14:34
If I'm understanding this correctly, you  need the same enhancement to jsprit i suggested for periodic problems https://github.com/jsprit/jsprit/issues/148
		
        
		
		 ---- On Tue, 19 May 2015 15:16:36 +0100  notifications@github.com  wrote ----Isn't this going to slow the calculation down by adding in to much orders?
And if the order with time window gets planned in on monday and tuesday than it is planned in twice

**Comment by oblonski** [comment] 2015-05-19 17:17
Ahh ok. Then I relate this to #148.

**Comment by PGWelch** [comment] 2015-05-19 18:42
If I'm correct (Connor, please let me know if otherwise), we're saying at least part of your problem is that you have a job and multiple slots when this job could be done e.g. 'day 3, 10:00 to 12:00' or 'day 5, 13:00 to 16:00'or XXX etc. This comes down to the optimiser understanding it has to do this job, or this job, but not both, and in the recreate it should systematically try each job and insert the cheapest. So its basically the same as a periodic problem where your different visit patterns only have one visit each.

**Comment by demonicmetalcs** [comment] 2015-05-20 07:08
It is not related to #148.
We have an order that can be done  on 
monday 8:00 to 17:00
tuesday 8:00 to 17:00
Friday 12:00 to 17:00
but has to be done only once. this is for example the openings times of the location

but we also have an order that has to be done before say 25-5-2015 17:00

and we have orders that have no time constraint at all.

Than we have the mechanics 
monday 8:00 to 17:00
tuesday 8:00 to 17:00
wednesday 8:00 to 12:00
etc.

What we do right now is do the calculations for 1 day, take away the scheduled orders from the batch and do another calculation for the next day etc. etc. till we have scheduled a full month.
this method takes up long time and gives the best results at the start of the month and gets  
worse at the end.

so what we want to do is do this in one calculation.

the mechanics we can do by implementing multiple vehicles.
the orders with no time constrain can just be added and the order with an done before can be added with an regular time window.

but the problem is with the once that have opening times of the location

**Comment by oblonski** [comment] 2015-05-20 07:31
Ok. Now I understand.

> this method takes up long time and gives the best results at the start
> of the month and gets
>
> worse at the end.
>

Great to learn. Thank you. This might be the main drawback of this
approach. But it is actually smth I would also expect when thinking
about it thoroughly. The optimization picks the cherries at the
beginning and at the end there are no cherries anymore :).

Am 20/05/15 um 09:08 schrieb demonicmetalcs:
>
> It is not related to #148 <https://github.com/jsprit/jsprit/issues/148>.
> We have an order that can be done on
> monday 8:00 to 17:00
> tuesday 8:00 to 17:00
> Friday 12:00 to 17:00
> but has to be done only once. this is for example the openings times
> of the location
>

Ok. This is the crux. It needs to be modelled with multiple time-windows
which cannot be done yet :(. For now I can only recommend you to
distribute the "cherries" equally among your planning period. Once
multiple time windows are available, you can model it the way Phil and I
suggested in the first place.

**Comment by demonicmetalcs** [comment] 2015-05-20 07:33
Can you give any indication of the date of multiple time windows?

**Comment by PGWelch** [comment] 2015-05-20 08:12
If jsprit could model 'do this stop A' or 'do this stop B' or 'do this stop C' (i.e. a simpler version of what I've suggested for periodic problems), then this is actually modelling multiple time windows, as each stop could be identical apart from its (single) time window. I also suspect its probably a lot simpler to implement multiple time windows in this manner.

**Comment by oblonski** [comment] 2015-05-20 08:42
Considering my time I do not like to fix a certain date. Hope you understand. 

BTW: @the method takes up long time. What kind of algorithm config do you use for solving your problem?

**Comment by oblonski** [comment] 2015-05-20 08:43
@PGWelch I completely aggree :)

**Comment by PGWelch** [comment] 2015-05-20 09:24
Hi Connor,The point about #148 is that you would use it to model your order that could be done on multiple days with different time windows on the days, but done once only. To the best of my knowledge, you wouldn't be able to optimise this effectively in the current jsprit.
		
        Best regards, Phil 
		
		 ---- On Wed, 20 May 2015 08:08:08 +0100  notifications@github.com  wrote ----It is not related to #148.
We have an order that can be done  on 
monday 8:00 to 17:00
tuesday 8:00 to 17:00
Friday 12:00 to 17:00
but has to be done only once. this is for example the openings times of the location
but we also have an order that has to be done before say 25-5-2015 17:00
and we have orders that have no time constraint at all.
Than we have the mechanics 
monday 8:00 to 17:00
tuesday 8:00 to 17:00
wednesday 8:00 to 12:00
etc.
What we do right now is do the calculations for 1 day, take away the scheduled orders from the batch and do another calculation for the next day etc. etc. till we have scheduled a full month.
this method takes up long time and gives the best results at the start of the month and gets
worse at the end.
so what we want to do is do this in one calculation.
the mechanics we can do by implementing multiple vehicles.
the orders with no time constrain can just be added and the order with an done before can be added with an regular time window.
but the problem is with the once that have opening times of the location

**Comment by demonicmetalcs** [comment] 2015-05-21 09:02
I understand that you don't fix a date.

I have converted my code to the multiple vehicles and just ignored the openings times.
Now i can calculate a month with 60 mechanics and 2000 orders in under 3 hours.
This is amazing.

we have translated the code to C# and we get regular outofmemoryexceptions.
the first on was on the FastVehicleRoutingTransportCostsMatrix (thanks to bad translation)
the next one is on the StateManager(possibly to bad translation)

what is the order/ vehicle limit you tested for?

also i have am trying to implement multiple time windows through constraints 

private VehicleRoutingTransportCosts routingCosts;
            private Dictionary<Guid, TimeWindow[]> timeWindows = new Dictionary<Guid, TimeWindow[]>();
            
            public HardActivityConstraint_ConstraintsStatus fulfilled(JobInsertionContext iFacts, TourActivity prevAct, TourActivity newAct, TourActivity nextAct, double prevActDepTime)
            {
                if (!timeWindows.Keys.Contains(Guid.Parse(newAct.Location.Id))) return HardActivityConstraint_ConstraintsStatus.FULFILLED;
                TimeWindow[] timeWindow = timeWindows[Guid.Parse(newAct.Location.Id)];
                

                double transporttime = routingCosts.getTransportTime(prevAct.Location, newAct.Location, 0, iFacts.NewDriver, iFacts.NewVehicle);
                double ariveTime =  prevActDepTime + transporttime;
                if (timeWindow.Any(window => ariveTime <= window.End && ariveTime >= window.Start))
                {
                    return HardActivityConstraint_ConstraintsStatus.FULFILLED;
                }
                return HardActivityConstraint_ConstraintsStatus.NOT_FULFILLED;

but what happens is the order gets planned outside the timewindows, so the route is notfulfilled.
but the next time it gets planned on the same time as before.
do you have any ideas?

**Comment by karussell** [comment] 2015-05-21 09:03
> outofmemoryexceptions

why not increase the RAM you give the VM?

**Comment by oblonski** [comment] 2015-05-21 09:06
> I have converted my code to the multiple vehicles and just ignored the
> openings times.
> Now i can calculate a month with 60 mechanics and 2000 orders in under
> 3 hours.
> This is amazing.
>

What config/algorithm you use? Do you use threading? Please have in mind
that you might need more iterations than the default one. This is what
you need to figure out.


> we have translated the code to C# and we get regular
> outofmemoryexceptions.
> the first on was on the FastVehicleRoutingTransportCostsMatrix (thanks
> to bad translation)
> the next one is on the StateManager(possibly to bad translation)
>

Here I cannot help. Sorry.

**Comment by PGWelch** [comment] 2015-05-21 09:16
(I believe) increasing the RAM you give the VM won't work if its in C#, as C# manages the RAM differently (it knows about the amount of memory available in the whole system and manages accordingly if I remember correctly).

How did you convert to C#? Did you literally just recode each line or did you use some automated process?

**Comment by demonicmetalcs** [comment] 2015-05-21 09:22
@karussell @PGWelch  is correct it is not that i am out of ram but the total size of one object may not exceed 2 GB and it has to be located in one piece on the memory.

We used an automated process and than some errors had to be resolved. but this means that the code can be optimized. as i already didwith the  FastVehicleRoutingTransportCostsMatrix.

@oblonski the 3 hours is with the IterationWithoutImprovementTermination(100) so i think this is an fair result and time

**Comment by oblonski** [comment] 2015-05-21 09:24
I meant which algorith do use.

Jsprit.createAlgorithm ?

or

Schrimpf?

or

any other



Am 21/05/15 um 11:22 schrieb demonicmetalcs:

**Comment by demonicmetalcs** [comment] 2015-05-21 09:26
var searchStrategy = new HierarchicalConfiguration(ConfigurationType.SearchStrategy)
                {
                    Name = "radialRuinAndRecreate",
                    SelectorName = "selectBest",
                    AcceptorName = "schrimpfAcceptance",
                    Probability = 0.5,
                    Alpha = 0.1,
                    Warmup = 20
                };
                algorithm.Configurations.Add(searchStrategy);

                var module = new HierarchicalConfiguration(ConfigurationType.Module)
                {
                    Name = "ruin_and_recreate",
                    RuinShare = "0.5",
                    InsertionName = "bestInsertion",
                    Probability = 0.5,
                    RuinName = "randomRuin"
                };
                searchStrategy.Configurations.Add(module);

                searchStrategy = new HierarchicalConfiguration(ConfigurationType.SearchStrategy)
                {
                    Name = "radialRuinAndRecreate",
                    SelectorName = "selectBest",
                    AcceptorName = "schrimpfAcceptance",
                    Probability = 0.5,
                    Alpha = 0.1,
                    Warmup = 20
                };
                algorithm.Configurations.Add(searchStrategy);
                module = new HierarchicalConfiguration(ConfigurationType.Module)
                {
                    Name = "ruin_and_recreate",
                    RuinShare = "0.3",
                    InsertionName = "bestInsertion",
                    Probability = 0.5,
                    RuinName = "radialRuin"
                };

                searchStrategy.Configurations.Add(module);

                var insertion = new HierarchicalConfiguration(ConfigurationType.Insertion)
                {
                    Name = "bestInsertion",
                    RuinShare = "0.5",
                    InsertionName = "bestInsertion",
                    Probability = 1.0,
                    RuinName = "randomRuin"
                };

**Comment by PGWelch** [comment] 2015-05-21 09:54
@demonicmetalcs what was the automated code translation process you used? (it's not relevant to your problem, but I'm interested). Also you should avoid objects - e.g. very large arrays - that may need to allocate more than a few tens or one hundred MB of continuous memory. This will be a problem on any system, dependent on memory fragmentation. You may just need to recode this bit. Assuming you're doing something array-like, you could have something which implements IList<double> but actually allocates multiple memory blocks under the hood?

**Comment by demonicmetalcs** [comment] 2015-05-21 09:59
@PGWelch http://www.tangiblesoftwaresolutions.com/

the code from the statemanager is
vehicle_dependent_activity_states = new object[nuActivities][nuVehicleTypeKeys][stateIndexCounter+1];

this i am trying to convert into something that allocates multiple memory blocks, because 4000 activities and 1000 vehicles gives me an OOM

**Comment by oblonski** [comment] 2015-05-21 10:00
ahh ok. the schrimpf one. try to also use
```
Jsprit.createAlgorithm(...)
```
see also https://github.com/jsprit/jsprit/blob/master/WHATS_NEW.md

It use more sophisticated strategies which makes the algorithm generally slower. However, it scales better with size - I think, since what is removed has actually a hard absolute upper bound (in contrary to the schrimpf approach which always removes 50% of the customers, i.e. 1000 in your case).
It is recommended to use multiple threads when using the jsprit algo. You can simply do this:
```ehicleRoutingAlgorithm algorithm = Jsprit.Builder.newInstance(problem).setProperty(Parameter.THREADS,"5").buildAlgorithm();```
and you ll run the algorithm five threads. If I were you I d try noThreads = noCores + 1.

**Comment by demonicmetalcs** [comment] 2015-05-21 10:06
Thank you i am going to translate the jsprit class now.
About the thread they are implemented in an java way. this will need a lot of time to be reworked to C# so at the moment i am using 1 thread.
i will inform you with the results when i get them

**Comment by demonicmetalcs** [comment] 2015-06-11 08:02
After some testing and tweaking 

these are the settings 
workdays are 8 to 17 Monday to Friday
number of iteration 2000
stop after 100 iteration without improvement
orders longer than 6 hours get split in to orders of 2.

these are our results.

60 mechanics 601 orders 1 month(mei 2015) release
adding orders 00:00:01.3425535
Build Fast Cost Matrix 00:00:00.6342697
add routconstarints 00:00:00.0017027
create jsprit 00:00:04.5437341
total before  jsprit 00:00:08.8010275
Iteraties run20
Iteraties run411
total jsprit 00:49:58.9397984

the question we have is that as you can see the iterations stop improving after 311.
is this expected with this data set or could this be because of some of our settings?

**Closed** 2015-07-29 19:32 UTC
Labels: question
