### ISSUE TITLE
Driver break locations can become fixed at vehicle start location

### ISSUE THREAD

**Issue by nottsmcr** [jsprit/jsprit#191] opened 2015-10-12 18:20 UTC
You're in luck with repeatability; I pulled some unusual data and managed to exasperate the problem. Which potentially says something about the problem - when the distance from the warehouse to the majority of the delivery locations is large (and therefore more expensive), I wonder if there is some conflict on the algorithm override (which balances the high cost of not having a lunch break) that then makes the lunch break become associated with location number of the vehicle?

Essentially the problem is sporadic, whereby a lunch break loses its variable location status and defaults back to the driver start location. Attached is a distance matrix (km), time matrix (mins) - they are of the format (from, to, value) - a csv I created to show the arrival and departure times of my solution, and the code setup of the override (which I believe to still be the same as you wrote in the example in every way, just horribly formatted in a .txt). You can see that the long service time for the lunch means that 3 jobs are kicked to unassigned.

https://drive.google.com/folderview?id=0B-8kpqeqJb9ZTzZJNDZNcTZ1NE0&usp=sharing

Edit: Note you also don't have to be so strict on the lunch break times for this to happen. I was testing whether the issue arises because the window for the lunch break was larger than the duration of the break. It makes no difference as far as I can see.

**Comment by oblonski** [comment] 2015-10-12 21:59
Thanks a lot. I am going to look into it. What do you mean by "you also don't have to be so strict on the lunch break times for this to happen". Do you mean that it is more important to assign jobs rather than breaks?

**Comment by nottsmcr** [comment] 2015-10-13 07:16
Apologies, I wasn't clear. In the example code I sent, the lunch break is given a small (20 minute) window in which it can be "delivered". This would, at least I think, make it more likely that routes are generated with the lunch break unassigned, thus causing the cost penalty override to be applied. You could give the lunch break a wider window in which it can be taken and the problem still occurs, though.

With the random component to the problem appearing, I'm trying to identify "special" measures the code takes which then gives the break location an identity. In LocalActivityInsertionCostsCalculator, you appear to have initially added some provision for breaks being handled differently, perhaps you had something in mind here as a problem?

**Comment by nottsmcr** [comment] 2015-10-13 11:25
I don't know if this provides any further help to you in tracking things down but I have since found that solving for multiple drivers, each with their own lunch break, it is possible to get a mixture of behaviour i.e. some drivers have breaks that function as expected, whilst others have breaks at the start location. 

This would at least imply that the variable location tag is overwritten on an individual job insertion level (when some unknown set of circumstances is faced), rather than suddenly hitting a bypass on variable location consideration. 

I'm running lots of tests to try and narrow it down further. Do you have any suggestions on where specifically I might want to set up additional monitoring?

**Comment by oblonski** [comment] 2015-10-13 18:50
Thanks. I just speed up regret insertion for problems with breaks. Breaks added 60-100% computation time. With https://github.com/jsprit/jsprit/commit/10defbe1eca44c6fd9e5aec2a529a653dd068609 it comes with almost no overhead.
Now it makes much more fun to figure out where the bug you detected comes from.

**Comment by nottsmcr** [comment] 2015-10-14 05:45
Hi. I have found that the clustering algorithm fails if you don't specify:

.setProperty(Jsprit.Strategy.CLUSTER_REGRET, "0.") before
.setProperty(Jsprit.Strategy.CLUSTER_BEST, "0.")

i.e. CLUSTER_BEST or any of the other hashed out options on their own will cause an error, but I'm also not quite sure what the double value means. If you don't have CLUSTER_REGRET active then it makes a call to the distance/time matrix for the break locations and throws an error. Could you point me to the right resource for understanding what you are doing with 10defbe?

**Comment by oblonski** [comment] 2015-10-14 05:56
I just made it faster by pulling out breaks from the regret calculation. It did not make any sense anyway to have them included. Later, I might refactor it such that I do not have a specific Break handler within RegretInsertion. But for now, it is - I think - pretty decent.

`.setProperty(Jsprit.Strategy.CLUSTER_REGRET, "0.")` means that the probablity of choosing this strategy module is zero, i.e. it is never chosen. And CLUSTER_REGRET is basically a combination of cluster-ruin and regret insertion. Thus, if you specify it like you in your last post, the neither `CLUSTER_REGRET` nor `CLUSTER_BEST` are supposed to chosen. If the are, open an issue since then it is a bug.

**Comment by nottsmcr** [comment] 2015-10-14 08:14
Ok, that makes sense. It is not a bug then because it is the fact that I did *not* specify that CLUSTER_REGRET is 0% that was causing the call to the distance/time matrix for the break location.

Please can you explain to me the implementation of the 10defbe method you mentioned in relation to my current algorithm setup on googledrive?

**Comment by oblonski** [comment] 2015-10-14 08:28
Exactly. The modification relates to your example such that the algorithm is just faster when dealing with breaks ... almost as fast as without breaks.

**Comment by nottsmcr** [comment] 2015-10-14 16:43
Hi again. The problem appears to be related to the cost penalty of not having a lunch break in the route. I dropped this cost penalty magnitude significantly and suddenly a large problem that I had 100% chance of duplicated previously, disappeared. I have not tested it on the data that I passed to you, but if you have a file set up to parse all those entries, I'd be interested to know if that problem goes away too.

It is not confined to a single search strategy, I tested each in isolation.

Now the *really* fun part. The location does not actually have to be the driver start location. When all drivers start in the same location, and the surplus of drivers is such that, even on the first iteration nothing is unassigned, somehow the breaks are actually able to acquire *a* location. I do not know where this location is or how I could possibly determine it.

**Comment by oblonski** [comment] 2015-10-14 16:53
Ok. I am testing it. I do not understand the fun part. Is it good or bad, i.e. is it funny because it is so weird? Or is it fun because it is so good?

**Comment by oblonski** [comment] 2015-10-14 16:54
And thanks for your analysis :+1:

**Comment by nottsmcr** [comment] 2015-10-14 16:56
Funny in that it's weird. I could possibly understand how it might default back to the driver start location somehow, but the ability of it to acquire a seemingly random location and not throw an error when it references the distance/time matrix... I can't understand what aspect has to fail in order for that to be possible. But I hope the strangeness of it helps you pinpoint it quicker.

**Comment by oblonski** [comment] 2015-10-14 16:58
Ahh ok. Thanks for your help, I ll check this asap.

**Comment by nottsmcr** [comment] 2015-10-14 17:04
No prob. The other strange part - why should the cost penalty of the break not being in the route have influence on this anyway? The cost penalty custom spec in the algorithm is set as an if function: 

if (vehicleHasBreak && !routeHasBreak)
	costs += 1000.;
	costs += vrp.getTransp....

If there is a surplus of drivers and no orders are unassigned from the start of the search strategy, then this cost add-on should be ignored. Yet increasing/decreasing it does appear to have an influence.

**Comment by nottsmcr** [comment] 2015-10-14 22:09
I now think my last post could be misleading. The change of costs for breaks not being in the route held for many tests for me, but the problem suddenly reappeared.

**Comment by oblonski** [comment] 2015-10-16 07:20
I just tried to reproduce the bug by setting up the problem you sent. This is my solution:
```
+--------------------------------------------------------------------------------------------------------------------------------+
| detailed solution                                                                                                              |
+---------+----------------------+-----------------------+-----------------+-----------------+-----------------+-----------------+
| route   | vehicle              | activity              | job             | arrTime         | endTime         | costs           |
+---------+----------------------+-----------------------+-----------------+-----------------+-----------------+-----------------+
| 1       | 0                    | start                 | -               | undef           | 540             | 0               |
| 1       | 0                    | service               | 12              | 612             | 622             | 41              |
| 1       | 0                    | service               | 15              | 633             | 643             | 47              |
| 1       | 0                    | service               | 17              | 643             | 653             | 47              |
| 1       | 0                    | service               | 14              | 658             | 668             | 49              |
| 1       | 0                    | service               | 13              | 671             | 681             | 51              |
| 1       | 0                    | service               | 18              | 681             | 691             | 51              |
| 1       | 0                    | service               | 8               | 694             | 704             | 52              |
| 1       | 0                    | service               | 3               | 706             | 716             | 53              |
| 1       | 0                    | service               | 4               | 721             | 731             | 55              |
| 1       | 0                    | service               | 10              | 736             | 746             | 57              |
| 1       | 0                    | service               | 16              | 748             | 758             | 58              |
| 1       | 0                    | service               | 7               | 767             | 777             | 63              |
| 1       | 0                    | break                 | lunch           | 777             | 825             | 64              |
| 1       | 0                    | service               | 2               | 896             | 906             | 105             |
| 1       | 0                    | service               | 9               | 915             | 925             | 109             |
| 1       | 0                    | service               | 19              | 925             | 935             | 109             |
| 1       | 0                    | service               | 6               | 935             | 945             | 109             |
| 1       | 0                    | service               | 5               | 945             | 955             | 109             |
| 1       | 0                    | service               | 1               | 955             | 965             | 109             |
| 1       | 0                    | service               | 11              | 976             | 986             | 114             |
| 1       | 0                    | end                   | -               | 999             | undef           | 120             |
+--------------------------------------------------------------------------------------------------------------------------------+
```
when using these params:
```
 int driverNum = 1;  //solve for single driver
        int lunchStartTime = 780;
        int lunchEndTime = 840;
        int driverStartTime = 540;
        int driverEndTime = 1080;
        int servicetime = 10;
        int lunchLength = 45;
```

Thus the break is assigned location 7 which is the service before the break which is perfect. So still hard for me to reproduce it.

**Comment by nottsmcr** [comment] 2015-10-19 18:19
Interesting. I did a fresh install of the main branch and it has almost gone: one of the drivers had a 2 minute gap between their last delivery and a break, then a real driving time to the next job. That is out of ~40 drivers over two days. Previously I was working on the experimental branch for driver breaks. This makes me think it's possible that the asymmetrical distance/time matrix could be behind it (to describe the 2 minute discrepancy in the fresh install) and perhaps I made a mistake in changing this parameter to asymmetrical.

As it stands, the current Master branch doesn't seem affected except for the 2 min discrepancy, so perhaps best to close this and I will raise again if I see something unusual?

**Comment by nottsmcr** [comment] 2015-10-19 18:21
And thank you for looking into it for me.

**Comment by oblonski** [comment] 2015-10-20 06:50
Thanks for pointing me to the 2min - symetric/asymetric issue ... I am investigating this and give you a note then.

**Comment by nottsmcr** [comment] 2015-10-20 10:53
It is perhaps worth investigation, but it could also have been an anomaly that came in through my support code. Another 40 drivers went through fine today with zero problem.

**Comment by oblonski** [comment] 2015-11-05 07:50
I just close this for now.

**Closed by oblonski** 2015-11-05 07:50 UTC
Labels: bug
